### ISSUE TITLE
Bloquear Arquivos

### ISSUE THREAD

**Issue by luanrodriguespigosso** [webviewtech/site-webview#7]
Criar regra de bloqueio aos arquivos dos site.

Ex: https://webview.dev.br/

![Screenshot_20210914-064511.png](https://user-images.githubusercontent.com/32944691/133235373-98de3038-ffea-4785-9f61-041c35e45b7b.png)

**Comment by webviewtech** [comment]
Não será realizado o bloqueio, entendemos que não utilizamos qualquer dado sensível até o presente momento, será reaberta a issue quando houver necessidade.
